// Auto-generated by new-client.sh
// This is a placeholder homepage. You should replace it with a business-type specific component.
import Hero from '@/app/components/Hero';
import Features from '@/app/components/Features/Features';
import HowItWorksSection from '@/app/components/HowItWorksSection/HowItWorksSection';
import { NextPage } from 'next';

// Import the TestimonialsSection component and types
import { TestimonialsSection, type TestimonialData } from '@/app/components/TestimonialsSection';

// Define dummy testimonial data
const DUMMY_TESTIMONIALS: TestimonialData[] = [
  {
    id: '1',
    quote: "Within weeks, we jumped from invisible to dominating our local rankings. The heatmaps were game-changing!",
    author: {
      name: "Mike Patterson",
      title: "Evergreen Landscapes",
      avatarSrc: "/drew-cano.png" // Example, replace with actual avatar paths
    }
  },
  {
    id: '2',
    quote: "Gruntworks transformed our lead generation. We're booked months in advance!",
    author: {
      name: "Jordan Burgess",
      title: "Peak Performance Lawns",
      avatarSrc: "/jordan-burgess.png"
    }
  },
  {
    id: '3',
    quote: "The insights and tools provided are unparalleled. Highly recommend for any landscaping biz.",
    author: {
      name: "Lyle Kauffman",
      title: "Sunrise Gardening Co.",
      avatarSrc: "/lyle-kauffman.png"
    }
  }
];

const HomePage: NextPage = () => {
  return (
    <main>
      <Hero />
      <Features />
      <HowItWorksSection />
      {/* Add the TestimonialsSection */}
      <TestimonialsSection
        title="Real Landscapers, Real Wins"
        subtext="Hear from mid-sized landscapers thriving with Gruntworks."
        testimonials={DUMMY_TESTIMONIALS}
      />
    </main>
  );
};

export default HomePage;
