// Auto-generated by new-client.sh
// This is a placeholder homepage. You should replace it with a business-type specific component.
import clientSettings from '@/config/client';
import { NextPage } from 'next';

const HomePage: NextPage = () => {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <div className="text-center">
        <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
          Welcome to {clientSettings.businessName}
        </h1>
        <p className="mt-6 text-lg leading-8 text-gray-600">
          We are a leading provider of {clientSettings.businessType} services in {clientSettings.cityState}.
        </p>
        <p className="mt-4 text-md text-gray-500">
          Client Slug: {clientSettings.clientSlug}
        </p>
        <div className="mt-10 flex items-center justify-center gap-x-6">
          <a
            href="#"
            className="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Get started
          </a>
          <a href="#" className="text-sm font-semibold leading-6 text-gray-900">
            Learn more <span aria-hidden="true">→</span>
          </a>
        </div>
        <div className="mt-8">
          <h2 className="text-2xl font-semibold">Contact Us:</h2>
          <p>Email: {clientSettings.contactEmail}</p>
          <p>Phone: {clientSettings.contactPhone}</p>
          <p>Address: {clientSettings.contactAddress}</p>
        </div>
      </div>
    </main>
  );
};

export default HomePage;
