# Client specific configurations
# This file is auto-generated by new-client.sh
# Review and update with actual client data.

export interface ClientSettings {
  businessName: string;
  businessType: string; // 'general'
  cityState: string; // 'global-hq'
  clientSlug: string; // 'client-gruntworks agency-global-hq'
  contactEmail?: string;
  contactPhone?: string;
  contactAddress?: string;
  siteUrl?: string;
  // Add other client-specific settings here
  logoUrl?: string;
  primaryColor?: string; // e.g., '#FF5733'
  secondaryColor?: string; // e.g., '#33FF57'
  services?: Service[];
  socialMedia?: {
    facebook?: string;
    twitter?: string;
    linkedin?: string;
    instagram?: string;
    youtube?: string;
  };
  // SEO related settings
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string[];
}

export interface Service {
  name: string;
  description: string;
  imageUrl?: string;
  slug: string;
}

export const clientSettings: ClientSettings = {
  businessName: process.env.NEXT_PUBLIC_BUSINESS_NAME || "Gruntworks Agency",
  businessType: process.env.NEXT_PUBLIC_BUSINESS_TYPE || "general",
  cityState: process.env.NEXT_PUBLIC_CITY_STATE || "global-hq",
  clientSlug: process.env.NEXT_PUBLIC_CLIENT_SLUG || "client-gruntworks agency-global-hq",
  contactEmail: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "contact@example.com",
  contactPhone: process.env.NEXT_PUBLIC_CONTACT_PHONE || "(555) 123-4567",
  contactAddress: process.env.NEXT_PUBLIC_CONTACT_ADDRESS || "123 Main St, Anytown, USA",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://www.example.com",
  // Initialize other settings with defaults or placeholders
  logoUrl: "/logo-placeholder.png", // Replace with actual logo path
  primaryColor: "#007bff", // Example primary color (Tailwind's blue-500)
  secondaryColor: "#6c757d", // Example secondary color (Tailwind's gray-500)
  services: [
    {
      name: "Sample Service 1",
      description: "Description for sample service 1.",
      slug: "sample-service-1",
      imageUrl: "/service1-placeholder.jpg",
    },
    {
      name: "Sample Service 2",
      description: "Description for sample service 2.",
      slug: "sample-service-2",
      imageUrl: "/service2-placeholder.jpg",
    },
  ],
  socialMedia: {
    facebook: "https://facebook.com/yourpage",
    twitter: "https://twitter.com/yourprofile",
  },
  metaTitle: ,
  metaDescription: ,
  keywords: ["general", "global-hq", "Gruntworks Agency"],
};

export default clientSettings;

